logLevel: info
port: 3131

#docker:
#  repoUrl:
#  username:
#  password:
#
#nats:
#  tag: latest
#  containerName: nats_dev
#  clusterName: NATS
#  serverPort: 4222
#  monitoringPort: 8222
#
#redis:
#  tag: alpine
#  containerName: redis_dev
#  port: 6379
#
#opa:
#  tag: latest
#  containerName: opa_dev
#  port: 8181
#
#postgres:
#  tag: alpine
#  containerName: postgresd_dev
#  port: 5432
#  user: hydra
#  password: dev
#  db: hydra
#
#hydra:
#  tag: v2.2.0-rc.3
#  publicPort: 4444
#  adminPort: 4445
#  tokenPort: 5555
#  secretsSystem: youReallyNeedToChangeThis
#  pairwiseSalt: youReallyNeedToChangeThis
#  dsn: postgres://hydra:dev@postgresd_dev:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
#  migrate:
#    tag: v2.2.0-rc.3
#  consent:
#    tag: v2.2.0-rc.3
#    port: 3000