apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-service"
spec:
  selector:
      app: "{{ .Chart.Name }}"
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-transmute-driver-service"
spec:
  selector:
      app: "{{ .Chart.Name }}-transmute-driver"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-uport-driver-service"
spec:
  selector:
      app: "{{ .Chart.Name }}-uport-driver"
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
