apiVersion: v2
name: hashicorp-vault
description: A Helm chart for vault

version: 1.0.0

appVersion: "1.0.0"

dependencies:
  - name: vault
    version: 0.27.0
    repository: https://helm.releases.hashicorp.com


