hashicorp/vault-helm:
  global:
   tlsDisable: true
  injector:
    enabled: false
    route:
      enabled: true
      host: '""'
  server:
    extraVolumes:
      - type: secret
        name: vault-tls
    standalone:
      config: |
        ui = true
        listener "tcp" {
          tls_disable = true
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/userconfig/vault-tls/tls.crt"
          tls_key_file  = "/vault/userconfig/vault-tls/tls.key"
        }
        storage "file" {
          path = "/vault/data"
        }
    ingress:
      enabled: false
      ingressClassName: "nginx"
      pathType: Prefix
      hosts:
        - host: vault.xfsc.dev
          paths:
            - /
      tls:
      - secretName: xfsc-wildcard
        hosts:
        - vault.xfsc.dev
