on:
  workflow_call:
    inputs:
      repo_name: 
         description: "Final Repo name"
         type: string
         default: ''
         required: false
    outputs:
      image_tag:
        description: "Sanitized image tag"
        value: ${{ jobs.setup.outputs.image_tag }}
      repo_name:
        description: "Final Repo name"
        value: ${{ jobs.setup.outputs.repo_name}}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}
      repo_name: ${{ steps.set-repo-name.outputs.repo_name }}
    env:
      CI_DEFAULT_BRANCH: 'main'
      CI_COMMIT_REF_NAME: ${{ github.ref_name }}
      CI_COMMIT_TAG: ${{ github.event.release.tag_name || '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set IMAGE_TAG
        id: set-tag
        run: |
          if [ -z "${IMAGE_TAG}" ]; then
            if [ "$CI_COMMIT_REF_NAME" == "$CI_DEFAULT_BRANCH" ]; then
              IMAGE_TAG="latest"
            elif [ -n "$CI_COMMIT_TAG" ]; then
              NOSLASH=$(echo "$CI_COMMIT_TAG" | tr -s / - )
              IMAGE_TAG="${NOSLASH//[^a-zA-Z0-9\-\.]/}"
            else
              NOSLASH=$(echo "$CI_COMMIT_REF_NAME" | tr -s / - )
              IMAGE_TAG="branch-${NOSLASH//[^a-zA-Z0-9\-]/}"
            fi
          fi
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
      - name: Set Repo Name
        id: set-repo-name
        run: |
          if [ -z "${{ inputs.repo_name }}" ]; then
            # Nutze den aktuellen GitHub Repo-Namen (nach dem Slash)
            IMAGE_REPO=$(basename "${GITHUB_REPOSITORY}")
          else
            IMAGE_REPO="${{ inputs.repo_name }}"
          fi
          
          echo "repo_name=$IMAGE_REPO" >> "$GITHUB_OUTPUT"
           
