name: Setup Build Context

on:
  workflow_call:
    outputs:
      image_tag:
        description: "Sanitized image tag"
        value: ${{ jobs.setup.outputs.image_tag }}

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}

    env:
      CI_DEFAULT_BRANCH: 'main'
      CI_COMMIT_REF_NAME: ${{ github.ref_name }}
      CI_COMMIT_TAG: ${{ github.event.release.tag_name || '' }}

    steps:
      - name: Set IMAGE_TAG
        id: set-tag
        run: |
          if [ -z "${IMAGE_TAG}" ]; then
            if [ "$CI_COMMIT_REF_NAME" == "$CI_DEFAULT_BRANCH" ]; then
              IMAGE_TAG="latest"
            elif [ -n "$CI_COMMIT_TAG" ]; then
              NOSLASH=$(echo "$CI_COMMIT_TAG" | tr -s / - )
              IMAGE_TAG="${NOSLASH//[^a-zA-Z0-9\-\.]/}"
            else
              NOSLASH=$(echo "$CI_COMMIT_REF_NAME" | tr -s / - )
              IMAGE_TAG="branch-${NOSLASH//[^a-zA-Z0-9\-]/}"
            fi
          fi
          echo "image_tag=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
