name: Eclipse Dash License Scan (Node.js)

on:
  workflow_call:

permissions:
  contents: read

jobs:
  dash-license-scan:
    name: Eclipse Dash License Scan for Node.js
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Eclipse Dash Licenses Tool
        run: |
          curl -sSL -o dash-licenses.jar \
            "https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST"

      - name: Run Dash license scan for Node.js
        env:
          TOKEN: ${{ secrets.GITLAB_API_TOKEN }}
        run: |
            DASH_ARGS="-repo https://github.com/${{ github.repository }} -review -project technology.xfsc -token $TOKEN"
          
            echo "📦 Found pnpm-lock.yaml – running Dash for pnpm..."
            java -Dorg.slf4j.simpleLogger.defaultLogLevel=debug -jar dash-licenses.jar $DASH_ARGS pnpm-lock.yaml
          elif [ -f package-lock.json ]; then
            echo "📦 Found package-lock.json – running Dash for npm..."
            java -Dorg.slf4j.simpleLogger.defaultLogLevel=debug -jar dash-licenses.jar $DASH_ARGS package-lock.json
          elif [ -f yarn.lock ]; then
            echo "📦 Found yarn.lock – running Dash for yarn..."
            java -Dorg.slf4j.simpleLogger.defaultLogLevel=debug -jar dash-licenses.jar $DASH_ARGS yarn.lock
          else
            echo "❌ No supported Node.js lockfile found (pnpm-lock.yaml, package-lock.json, or yarn.lock)."
            exit 1
          fi


