# .github/workflows/license-check.yml

name: License Check

on:
  workflow_call:
    inputs:
      requirements_path:
        description: 'Path to requirements.txt'
        required: true
        type: string

jobs:
  check-licenses:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies dry-run and transform output
        run: |
          pip install --upgrade pip
          pip install -r ${{ inputs.requirements_path }} --dry-run \
          | grep -Poh "(?<=^Would install ).*$" \
          | grep -oP '[^\s]+' \
          | sed -E -e 's|(.+)\-([a-zA-Z0-9\.]+)|pypi/pypi/-/\1/\2/' \
          > packages.txt

      - name: Download Eclipse Dash License Tool
        run: |
          mkdir -p dash-licenses
          curl -L -o dash-licenses/org.eclipse.dash.licenses.jar https://repo.eclipse.org/content/repositories/dash/org/eclipse/dash/licenses/1.3.0/org.eclipse.dash.licenses-1.3.0.jar

      - name: Run License Tool
        env:
          TOKEN: ${{ secrets.GITLAB_API_TOKEN }}
        run: |
          DASH_ARGS="-repo https://github.com/${{ github.repository }} -review -project technology.xfsc -token $TOKEN"
          java -jar dash-licenses/org.eclipse.dash.licenses.jar $DASH_ARGS - < packages.txt
