name: Eclipse Dash License Scan (Node.js)

on:
  workflow_call:

jobs:
  dash-license-scan:
    name: Eclipse Dash License Scan for Node.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Eclipse Dash Licenses Tool
        run: |
          curl -sSL -o dash-licenses.jar \
            "https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST"

      - name: Run Dash license scan for Node.js
        run: |
          if [ -f pnpm-lock.yaml ]; then
            echo "📦 Found pnpm-lock.yaml – running Dash for pnpm..."
            java -jar dash-licenses.jar \
              -repo "https://github.com/${{ github.repository }}" \
              pnpm-lock.yaml
          elif [ -f package-lock.json ]; then
            echo "📦 Found package-lock.json – running Dash for npm..."
            java -jar dash-licenses.jar \
              -repo "https://github.com/${{ github.repository }}" \
              package-lock.json
          else
            echo "❌ No supported Node.js lockfile found (pnpm-lock.yaml or package-lock.json)."
            exit 1
          fi
