name: Deploy Helm Chart (Org Workflow)

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  workflow_dispatch:

jobs:
  helm-deploy:
    uses: eclipse-xfsc/dev-ops/.github/workflows/helm-oci-push.yml@main
    secrets:
      HARBOR_USERNAME: ${{ secrets.HARBOR_USERNAME }}
      HARBOR_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
      HARBOR_HOST: ${{ secrets.HARBOR_HOST }}
      HARBOR_PROJECT: ${{ secrets.HARBOR_PROJECT }}
