name: Helm Chart Build & Push

on:
  workflow_call:

jobs:
  setup-context:
    uses: eclipse-xfsc/dev-ops/.github/workflows/build-context.yml@main
    secrets: inherit

  helm-push:
    needs: setup-context
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use IMAGE_TAG
        run: | 
          echo "The image tag is: ${{ needs.setup-context.outputs.image_tag }}"

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.13.0

      - name: Helm login to Harbor (OCI)
        run: |
          echo "${{ secrets.HARBOR_PASSWORD }}" | helm registry login "${{ secrets.HARBOR_OCI }}" \
            --username "${{ secrets.HARBOR_USERNAME }}" \
            --password-stdin

      - name: Find and Push Helm Charts
        run: |
          mkdir -p packaged_charts
          find . -type f -name "Chart.yaml" | grep "deployment/helm/" | while read chart; do
            CHART_DIR=$(dirname "$chart")
            CHART_NAME=$(basename "$CHART_DIR")
            helm dependency update "$CHART_DIR"
            helm package "$CHART_DIR" --destination packaged_charts
            PACKAGE_FILE=$(ls packaged_charts/${CHART_NAME}-*.tgz)
            helm push "$PACKAGE_FILE" oci://${{ secrets.HARBOR_OCI }}/${{ secrets.HARBOR_PROJECT }}
          done
