name: Universal Maven CI (Custom POM Path)

on:
  workflow_call:
    inputs:
      java_version:
        description: 'Java version to use'
        required: false
        default: '21'
        type: string

      folder:
        description: 'Path to folder containing pom.xml'
        required: false
        default: '.'
        type: string

jobs:
  maven-test:
    runs-on: ubuntu-latest
    name: Test ${{ inputs.folder }}
    defaults:
      run:
        working-directory: ${{ inputs.folder }}
    env:
      MAVEN_OPTS: >-
        -Dhttps.protocols=TLSv1.2
        -Dmaven.repo.local=.m2/repository
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
        -Dorg.slf4j.simpleLogger.showDateTime=true
        -Djava.awt.headless=true
      MAVEN_CLI_OPTS: >-
        --batch-mode --errors --fail-at-end --show-version
        -DinstallAtEnd=true -DdeployAtEnd=true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.java_version }}

      - uses: actions/cache@v3
        with:
          path: .m2/repository
          key: ${{ runner.os }}-m2-${{ inputs.folder }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Run Maven tests
        run: mvn $MAVEN_CLI_OPTS verify

      - name: Upload Surefire Reports
        uses: actions/upload-artifact@v4
        with:
          name: surefire-${{ inputs.folder }}
          path: '**/target/surefire-reports/TEST-*.xml'
