name: Maven Build & Test

on:
  workflow_call:

env:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=${{ github.workspace }}/.m2/repository
    -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true
  MAVEN_CLI_OPTS: >-
    --batch-mode --errors --fail-at-end --show-version
    -DinstallAtEnd=true -DdeployAtEnd=true

jobs:

  test:
    name: Maven Tests
    runs-on: ubuntu-latest
    container:
      image: maven:3.9-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven Repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Run tests
        run: mvn $MAVEN_CLI_OPTS verify

      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: '**/target/surefire-reports/TEST-*.xml'

  build-jib:
    name: Maven Jib Build
    runs-on: ubuntu-latest
    if: github.ref_type == 'branch' && github.ref_name == 'main' || github.ref_type == 'tag'
    container:
      image: maven:3.9-eclipse-temurin-21
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Maven Repo
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Jib Package & Build Image
        run: mvn $MAVEN_CLI_OPTS package jib:build -am
