name: Release SBOM with CycloneDX for Go

on:
  workflow_call:
     secrets:
      GH_TOKEN:
        required: true
jobs:
  go-cyclonedx-sbom:
    name: Generate SBOM with cyclonedx-gomod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go 1.23
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.8'

      - name: Install cyclonedx-gomod
        run: |
          go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@v1.9.0
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Generate SBOM with license info
        run: |
          cyclonedx-gomod mod -licenses -json -output sbom.json

      - name: Upload SBOM to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: sbom.json

      - name: Upload as artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: go-sbom
          path: sbom.json
